-- csv2mysql with arguments:
--   -o
--   1-define.sql
--   -u
--   -k
--   -p
--   -z
--   ADMISSIONS.csv
--   CALLOUT.csv
--   CAREGIVERS.csv
--   CHARTEVENTS.csv
--   CPTEVENTS.csv
--   DATETIMEEVENTS.csv
--   DIAGNOSES_ICD.csv
--   DRGCODES.csv
--   D_CPT.csv
--   D_ICD_DIAGNOSES.csv
--   D_ICD_PROCEDURES.csv
--   D_ITEMS.csv
--   D_LABITEMS.csv
--   ICUSTAYS.csv
--   INPUTEVENTS_CV.csv
--   INPUTEVENTS_MV.csv
--   LABEVENTS.csv
--   MICROBIOLOGYEVENTS.csv
--   NOTEEVENTS.csv
--   OUTPUTEVENTS.csv
--   PATIENTS.csv
--   PRESCRIPTIONS.csv
--   PROCEDUREEVENTS_MV.csv
--   PROCEDURES_ICD.csv
--   SERVICES.csv
--   TRANSFERS.csv
CREATE DATABASE IF NOT EXISTS mimic_sql;
USE mimic_sql;

DROP TABLE IF EXISTS ADMISSIONS;
DROP TABLE IF EXISTS CALLOUT;
DROP TABLE IF EXISTS CAREGIVERS;
DROP TABLE IF EXISTS CHARTEVENTS;
DROP TABLE IF EXISTS CPTEVENTS;
DROP TABLE IF EXISTS DATETIMEEVENTS;
DROP TABLE IF EXISTS DIAGNOSES_ICD;
DROP TABLE IF EXISTS DRGCODES;
DROP TABLE IF EXISTS D_CPT;
DROP TABLE IF EXISTS D_ICD_DIAGNOSES;
DROP TABLE IF EXISTS D_ICD_PROCEDURES;
DROP TABLE IF EXISTS D_ITEMS;
DROP TABLE IF EXISTS D_LABITEMS;
DROP TABLE IF EXISTS ICUSTAYS;
DROP TABLE IF EXISTS INPUTEVENTS_CV;
DROP TABLE IF EXISTS INPUTEVENTS_MV;
DROP TABLE IF EXISTS LABEVENTS;
DROP TABLE IF EXISTS MICROBIOLOGYEVENTS;
DROP TABLE IF EXISTS NOTEEVENTS;
DROP TABLE IF EXISTS OUTPUTEVENTS;
DROP TABLE IF EXISTS PATIENTS;
DROP TABLE IF EXISTS PRESCRIPTIONS;
DROP TABLE IF EXISTS PROCEDUREEVENTS_MV;
DROP TABLE IF EXISTS PROCEDURES_ICD;
DROP TABLE IF EXISTS SERVICES;
DROP TABLE IF EXISTS TRANSFERS;


CREATE TABLE IF NOT EXISTS ADMISSIONS (	-- rows=58976
   ROW_ID SMALLINT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED NOT NULL,
   ADMITTIME DATETIME NOT NULL,
   DISCHTIME DATETIME NOT NULL,
   DEATHTIME DATETIME,
   ADMISSION_TYPE VARCHAR(255) NOT NULL,	-- max=9
   ADMISSION_LOCATION VARCHAR(255) NOT NULL,	-- max=25
   DISCHARGE_LOCATION VARCHAR(255) NOT NULL,	-- max=25
   INSURANCE VARCHAR(255) NOT NULL,	-- max=10
   LANGUAGE VARCHAR(255),	-- max=4
   RELIGION VARCHAR(255),	-- max=22
   MARITAL_STATUS VARCHAR(255),	-- max=17
   ETHNICITY VARCHAR(255) NOT NULL,	-- max=56
   EDREGTIME DATETIME,
   EDOUTTIME DATETIME,
   DIAGNOSIS TEXT,	-- max=189
   HOSPITAL_EXPIRE_FLAG TINYINT UNSIGNED NOT NULL,
   HAS_CHARTEVENTS_DATA TINYINT UNSIGNED NOT NULL,
  UNIQUE KEY ADMISSIONS_ROW_ID (ROW_ID),	-- nvals=58976
  UNIQUE KEY ADMISSIONS_HADM_ID (HADM_ID)	-- nvals=58976
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS CALLOUT (	-- rows=34499
   ROW_ID SMALLINT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED NOT NULL,
   SUBMIT_WARDID TINYINT UNSIGNED,
   SUBMIT_CAREUNIT VARCHAR(255),	-- max=5
   CURR_WARDID TINYINT UNSIGNED,
   CURR_CAREUNIT VARCHAR(255),	-- max=5
   CALLOUT_WARDID TINYINT UNSIGNED NOT NULL,
   CALLOUT_SERVICE VARCHAR(255) NOT NULL,	-- max=5
   REQUEST_TELE TINYINT UNSIGNED NOT NULL,
   REQUEST_RESP TINYINT UNSIGNED NOT NULL,
   REQUEST_CDIFF TINYINT UNSIGNED NOT NULL,
   REQUEST_MRSA TINYINT UNSIGNED NOT NULL,
   REQUEST_VRE TINYINT UNSIGNED NOT NULL,
   CALLOUT_STATUS VARCHAR(255) NOT NULL,	-- max=8
   CALLOUT_OUTCOME VARCHAR(255) NOT NULL,	-- max=10
   DISCHARGE_WARDID TINYINT UNSIGNED,
   ACKNOWLEDGE_STATUS VARCHAR(255) NOT NULL,	-- max=14
   CREATETIME DATETIME NOT NULL,
   UPDATETIME DATETIME NOT NULL,
   ACKNOWLEDGETIME DATETIME,
   OUTCOMETIME DATETIME NOT NULL,
   FIRSTRESERVATIONTIME DATETIME,
   CURRENTRESERVATIONTIME DATETIME,
  UNIQUE KEY CALLOUT_ROW_ID (ROW_ID),	-- nvals=34499
  UNIQUE KEY CALLOUT_CURRENTRESERVATIONTIME (CURRENTRESERVATIONTIME)	-- nvals=1164
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS CAREGIVERS (	-- rows=7567
   ROW_ID SMALLINT UNSIGNED NOT NULL,
   CGID SMALLINT UNSIGNED NOT NULL,
   LABEL VARCHAR(255),	-- max=6
   DESCRIPTION VARCHAR(255),	-- max=21
  UNIQUE KEY CAREGIVERS_ROW_ID (ROW_ID),	-- nvals=7567
  UNIQUE KEY CAREGIVERS_CGID (CGID)	-- nvals=7567
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS CHARTEVENTS (	-- rows=263201375
   ROW_ID INT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED,
   ICUSTAY_ID MEDIUMINT UNSIGNED,
   ITEMID MEDIUMINT UNSIGNED NOT NULL,
   CHARTTIME DATETIME NOT NULL,
   STORETIME DATETIME,
   CGID SMALLINT UNSIGNED,
   VALUE TEXT,	-- max=91
   VALUENUM FLOAT,
   VALUEUOM VARCHAR(255),	-- max=17
   WARNING TINYINT UNSIGNED,
   ERROR TINYINT UNSIGNED,
   RESULTSTATUS VARCHAR(255),	-- max=6
   STOPPED VARCHAR(255),	-- max=8
  UNIQUE KEY CHARTEVENTS_ROW_ID (ROW_ID)	-- nvals=263201375
  )
  CHARACTER SET = UTF8;



CREATE TABLE  IF NOT EXISTS CPTEVENTS (	-- rows=573146
   ROW_ID MEDIUMINT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED NOT NULL,
   COSTCENTER VARCHAR(255) NOT NULL,	-- max=4
   CHARTDATE DATETIME,
   CPT_CD VARCHAR(255) NOT NULL,	-- max=5
   CPT_NUMBER MEDIUMINT UNSIGNED,
   CPT_SUFFIX VARCHAR(255),	-- max=1
   TICKET_ID_SEQ SMALLINT UNSIGNED,
   SECTIONHEADER VARCHAR(255),	-- max=25
   SUBSECTIONHEADER TEXT,	-- max=169
   DESCRIPTION VARCHAR(255),	-- max=30
  UNIQUE KEY CPTEVENTS_ROW_ID (ROW_ID)	-- nvals=573146
  )
  CHARACTER SET = UTF8;



CREATE TABLE  IF NOT EXISTS DATETIMEEVENTS (	-- rows=4486049
   ROW_ID MEDIUMINT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED,
   ICUSTAY_ID MEDIUMINT UNSIGNED,
   ITEMID MEDIUMINT UNSIGNED NOT NULL,
   CHARTTIME DATETIME NOT NULL,
   STORETIME DATETIME NOT NULL,
   CGID SMALLINT UNSIGNED NOT NULL,
   VALUE DATETIME,
   VALUEUOM VARCHAR(255) NOT NULL,	-- max=13
   WARNING TINYINT UNSIGNED,
   ERROR TINYINT UNSIGNED,
   RESULTSTATUS VARCHAR(255),	-- max=0
   STOPPED VARCHAR(255),	-- max=8
  UNIQUE KEY DATETIMEEVENTS_ROW_ID (ROW_ID)	-- nvals=4486049
  )
  CHARACTER SET = UTF8;


CREATE TABLE  IF NOT EXISTS DIAGNOSES_ICD (	-- rows=651047
   ROW_ID MEDIUMINT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED NOT NULL,
   SEQ_NUM TINYINT UNSIGNED,
   ICD9_CODE VARCHAR(255),	-- max=5
  UNIQUE KEY DIAGNOSES_ICD_ROW_ID (ROW_ID)	-- nvals=651047
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS DRGCODES (	-- rows=125557
   ROW_ID MEDIUMINT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED NOT NULL,
   DRG_TYPE VARCHAR(255) NOT NULL,	-- max=4
   DRG_CODE VARCHAR(255) NOT NULL,	-- max=4
   DESCRIPTION TEXT,	-- max=193
   DRG_SEVERITY TINYINT UNSIGNED,
   DRG_MORTALITY TINYINT UNSIGNED,
  UNIQUE KEY DRGCODES_ROW_ID (ROW_ID)	-- nvals=125557
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS D_CPT (	-- rows=134
   ROW_ID TINYINT UNSIGNED NOT NULL,
   CATEGORY TINYINT UNSIGNED NOT NULL,
   SECTIONRANGE VARCHAR(255) NOT NULL,	-- max=37
   SECTIONHEADER VARCHAR(255) NOT NULL,	-- max=25
   SUBSECTIONRANGE VARCHAR(255) NOT NULL,	-- max=11
   SUBSECTIONHEADER TEXT NOT NULL,	-- max=169
   CODESUFFIX VARCHAR(255),	-- max=1
   MINCODEINSUBSECTION MEDIUMINT UNSIGNED NOT NULL,
   MAXCODEINSUBSECTION MEDIUMINT UNSIGNED NOT NULL,
  UNIQUE KEY D_CPT_ROW_ID (ROW_ID),	-- nvals=134
  UNIQUE KEY D_CPT_SUBSECTIONRANGE (SUBSECTIONRANGE),	-- nvals=134
  UNIQUE KEY D_CPT_MAXCODEINSUBSECTION (MAXCODEINSUBSECTION)	-- nvals=134
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS D_ICD_DIAGNOSES (	-- rows=14567
   ROW_ID SMALLINT UNSIGNED NOT NULL,
   ICD9_CODE VARCHAR(255) NOT NULL,	-- max=5
   SHORT_TITLE VARCHAR(255) NOT NULL,	-- max=24
   LONG_TITLE TEXT NOT NULL,	-- max=222
  UNIQUE KEY D_ICD_DIAGNOSES_ROW_ID (ROW_ID),	-- nvals=14567
  UNIQUE KEY D_ICD_DIAGNOSES_ICD9_CODE (ICD9_CODE)	-- nvals=14567
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS D_ICD_PROCEDURES (	-- rows=3882
   ROW_ID SMALLINT UNSIGNED NOT NULL,
   ICD9_CODE VARCHAR(255) NOT NULL,	-- max=4
   SHORT_TITLE VARCHAR(255) NOT NULL,	-- max=24
   LONG_TITLE TEXT NOT NULL,	-- max=163
  UNIQUE KEY D_ICD_PROCEDURES_ROW_ID (ROW_ID),	-- nvals=3882
  UNIQUE KEY D_ICD_PROCEDURES_ICD9_CODE (ICD9_CODE),	-- nvals=3882
  UNIQUE KEY D_ICD_PROCEDURES_SHORT_TITLE (SHORT_TITLE)	-- nvals=3882
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS D_ITEMS (	-- rows=12478
   ROW_ID SMALLINT UNSIGNED NOT NULL,
   ITEMID MEDIUMINT UNSIGNED NOT NULL,
   LABEL TEXT,	-- max=95
   ABBREVIATION VARCHAR(255),	-- max=50
   DBSOURCE VARCHAR(255) NOT NULL,	-- max=10
   LINKSTO VARCHAR(255),	-- max=18
   CATEGORY VARCHAR(255),	-- max=27
   UNITNAME VARCHAR(255),	-- max=19
   PARAM_TYPE VARCHAR(255),	-- max=16
   CONCEPTID VARCHAR(255),	-- max=0
  UNIQUE KEY D_ITEMS_ROW_ID (ROW_ID),	-- nvals=12478
  UNIQUE KEY D_ITEMS_ITEMID (ITEMID)	-- nvals=12478
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS D_LABITEMS (	-- rows=755
   ROW_ID SMALLINT UNSIGNED NOT NULL,
   ITEMID SMALLINT UNSIGNED NOT NULL,
   LABEL VARCHAR(255) NOT NULL,	-- max=36
   FLUID VARCHAR(255) NOT NULL,	-- max=25
   CATEGORY VARCHAR(255) NOT NULL,	-- max=10
   LOINC_CODE VARCHAR(255),	-- max=7
  UNIQUE KEY D_LABITEMS_ROW_ID (ROW_ID),	-- nvals=755
  UNIQUE KEY D_LABITEMS_ITEMID (ITEMID)	-- nvals=755
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS ICUSTAYS (	-- rows=61532
   ROW_ID SMALLINT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED NOT NULL,
   ICUSTAY_ID MEDIUMINT UNSIGNED NOT NULL,
   DBSOURCE VARCHAR(255) NOT NULL,	-- max=10
   FIRST_CAREUNIT VARCHAR(255) NOT NULL,	-- max=5
   LAST_CAREUNIT VARCHAR(255) NOT NULL,	-- max=5
   FIRST_WARDID TINYINT UNSIGNED NOT NULL,
   LAST_WARDID TINYINT UNSIGNED NOT NULL,
   INTIME DATETIME NOT NULL,
   OUTTIME DATETIME,
   LOS FLOAT,
  UNIQUE KEY ICUSTAYS_ROW_ID (ROW_ID),	-- nvals=61532
  UNIQUE KEY ICUSTAYS_ICUSTAY_ID (ICUSTAY_ID)	-- nvals=61532
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS INPUTEVENTS_CV (	-- rows=17528894
   ROW_ID INT UNSIGNED NOT NULL,
   SUBJECT_ID SMALLINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED,
   ICUSTAY_ID MEDIUMINT UNSIGNED,
   CHARTTIME DATETIME NOT NULL,
   ITEMID SMALLINT UNSIGNED NOT NULL,
   AMOUNT FLOAT,
   AMOUNTUOM VARCHAR(255),	-- max=3
   RATE FLOAT,
   RATEUOM VARCHAR(255),	-- max=8
   STORETIME DATETIME NOT NULL,
   CGID SMALLINT UNSIGNED,
   ORDERID MEDIUMINT UNSIGNED NOT NULL,
   LINKORDERID MEDIUMINT UNSIGNED NOT NULL,
   STOPPED VARCHAR(255),	-- max=8
   NEWBOTTLE TINYINT UNSIGNED,
   ORIGINALAMOUNT FLOAT,
   ORIGINALAMOUNTUOM VARCHAR(255),	-- max=3
   ORIGINALROUTE VARCHAR(255),	-- max=20
   ORIGINALRATE FLOAT,
   ORIGINALRATEUOM VARCHAR(255),	-- max=5
   ORIGINALSITE VARCHAR(255),	-- max=20
  UNIQUE KEY INPUTEVENTS_CV_ROW_ID (ROW_ID)	-- nvals=17528894
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS INPUTEVENTS_MV (	-- rows=3618991
   ROW_ID MEDIUMINT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED NOT NULL,
   ICUSTAY_ID MEDIUMINT UNSIGNED,
   STARTTIME DATETIME NOT NULL,
   ENDTIME DATETIME NOT NULL,
   ITEMID MEDIUMINT UNSIGNED NOT NULL,
   AMOUNT FLOAT NOT NULL,
   AMOUNTUOM VARCHAR(255) NOT NULL,	-- max=19
   RATE FLOAT,
   RATEUOM VARCHAR(255),	-- max=12
   STORETIME DATETIME NOT NULL,
   CGID SMALLINT UNSIGNED NOT NULL,
   ORDERID MEDIUMINT UNSIGNED NOT NULL,
   LINKORDERID MEDIUMINT UNSIGNED NOT NULL,
   ORDERCATEGORYNAME VARCHAR(255) NOT NULL,	-- max=24
   SECONDARYORDERCATEGORYNAME VARCHAR(255),	-- max=24
   ORDERCOMPONENTTYPEDESCRIPTION VARCHAR(255) NOT NULL,	-- max=57
   ORDERCATEGORYDESCRIPTION VARCHAR(255) NOT NULL,	-- max=14
   PATIENTWEIGHT FLOAT NOT NULL,
   TOTALAMOUNT FLOAT,
   TOTALAMOUNTUOM VARCHAR(255),	-- max=2
   ISOPENBAG TINYINT UNSIGNED NOT NULL,
   CONTINUEINNEXTDEPT TINYINT UNSIGNED NOT NULL,
   CANCELREASON TINYINT UNSIGNED NOT NULL,
   STATUSDESCRIPTION VARCHAR(255) NOT NULL,	-- max=15
   COMMENTS_EDITEDBY VARCHAR(255),	-- max=15
   COMMENTS_CANCELEDBY VARCHAR(255),	-- max=15
   COMMENTS_DATE DATETIME,
   ORIGINALAMOUNT FLOAT NOT NULL,
   ORIGINALRATE FLOAT NOT NULL,
  UNIQUE KEY INPUTEVENTS_MV_ROW_ID (ROW_ID)	-- nvals=3618991
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS LABEVENTS (	-- rows=27872575
   ROW_ID INT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED,
   ITEMID SMALLINT UNSIGNED NOT NULL,
   CHARTTIME DATETIME NOT NULL,
   VALUE TEXT,	-- max=100
   VALUENUM FLOAT,
   VALUEUOM VARCHAR(255),	-- max=10
   FLAG VARCHAR(255),	-- max=8
  UNIQUE KEY LABEVENTS_ROW_ID (ROW_ID)	-- nvals=27872575
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS MICROBIOLOGYEVENTS (	-- rows=328446
   ROW_ID MEDIUMINT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED,
   CHARTDATE DATETIME NOT NULL,
   CHARTTIME DATETIME,
   SPEC_ITEMID MEDIUMINT UNSIGNED,
   SPEC_TYPE_DESC VARCHAR(255) NOT NULL,	-- max=56
   ORG_ITEMID MEDIUMINT UNSIGNED,
   ORG_NAME VARCHAR(255),	-- max=70
   ISOLATE_NUM TINYINT UNSIGNED,
   AB_ITEMID MEDIUMINT UNSIGNED,
   AB_NAME VARCHAR(255),	-- max=20
   DILUTION_TEXT VARCHAR(255),	-- max=6
   DILUTION_COMPARISON VARCHAR(255),	-- max=2
   DILUTION_VALUE SMALLINT UNSIGNED,
   INTERPRETATION VARCHAR(255),	-- max=1
  UNIQUE KEY MICROBIOLOGYEVENTS_ROW_ID (ROW_ID)	-- nvals=328446
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS NOTEEVENTS (	-- rows=2078705
   ROW_ID MEDIUMINT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED,
   CHARTDATE DATE NOT NULL,
   CHARTTIME DATETIME,
   STORETIME DATETIME,
   CATEGORY VARCHAR(255) NOT NULL,	-- max=17
   DESCRIPTION VARCHAR(255) NOT NULL,	-- max=80
   CGID SMALLINT UNSIGNED,
   ISERROR TINYINT UNSIGNED,
   TEXT MEDIUMTEXT,	-- max=55725
  UNIQUE KEY NOTEEVENTS_ROW_ID (ROW_ID)	-- nvals=2078705
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS OUTPUTEVENTS (	-- rows=4349339
   ROW_ID MEDIUMINT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED,
   ICUSTAY_ID MEDIUMINT UNSIGNED,
   CHARTTIME DATETIME NOT NULL,
   ITEMID MEDIUMINT UNSIGNED NOT NULL,
   VALUE FLOAT,
   VALUEUOM VARCHAR(255),	-- max=2
   STORETIME DATETIME NOT NULL,
   CGID SMALLINT UNSIGNED NOT NULL,
   STOPPED VARCHAR(255),	-- max=0
   NEWBOTTLE VARCHAR(255),	-- max=0
   ISERROR VARCHAR(255),	-- max=0
  UNIQUE KEY OUTPUTEVENTS_ROW_ID (ROW_ID)	-- nvals=4349339
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS PATIENTS (	-- rows=46520
   ROW_ID SMALLINT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   GENDER VARCHAR(255) NOT NULL,	-- max=1
   DOB VARCHAR(255) NOT NULL,	-- max=19
   DOD DATETIME,
   DOD_HOSP DATETIME,
   DOD_SSN DATETIME,
   EXPIRE_FLAG TINYINT UNSIGNED NOT NULL,
  UNIQUE KEY PATIENTS_ROW_ID (ROW_ID),	-- nvals=46520
  UNIQUE KEY PATIENTS_SUBJECT_ID (SUBJECT_ID)	-- nvals=46520
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS PRESCRIPTIONS (	-- rows=4156848
   ROW_ID MEDIUMINT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED NOT NULL,
   ICUSTAY_ID MEDIUMINT UNSIGNED,
   STARTDATE DATETIME,
   ENDDATE DATETIME,
   DRUG_TYPE VARCHAR(255) NOT NULL,	-- max=8
   DRUG VARCHAR(255),	-- max=58
   DRUG_NAME_POE VARCHAR(255),	-- max=58
   DRUG_NAME_GENERIC VARCHAR(255),	-- max=49
   FORMULARY_DRUG_CD VARCHAR(255),	-- max=17
   GSN TEXT,	-- max=125
   NDC VARCHAR(255),	-- max=11
   PROD_STRENGTH VARCHAR(255),	-- max=60
   DOSE_VAL_RX VARCHAR(255),	-- max=26
   DOSE_UNIT_RX VARCHAR(255),	-- max=32
   FORM_VAL_DISP VARCHAR(255),	-- max=47
   FORM_UNIT_DISP VARCHAR(255),	-- max=13
   ROUTE VARCHAR(255),	-- max=28
  UNIQUE KEY PRESCRIPTIONS_ROW_ID (ROW_ID)	-- nvals=4156848
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS PROCEDUREEVENTS_MV (	-- rows=258066
   ROW_ID MEDIUMINT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED NOT NULL,
   ICUSTAY_ID MEDIUMINT UNSIGNED,
   STARTTIME DATETIME NOT NULL,
   ENDTIME DATETIME NOT NULL,
   ITEMID MEDIUMINT UNSIGNED NOT NULL,
   VALUE FLOAT NOT NULL,
   VALUEUOM VARCHAR(255) NOT NULL,	-- max=4
   LOCATION VARCHAR(255),	-- max=24
   LOCATIONCATEGORY VARCHAR(255),	-- max=19
   STORETIME DATETIME NOT NULL,
   CGID SMALLINT UNSIGNED NOT NULL,
   ORDERID MEDIUMINT UNSIGNED NOT NULL,
   LINKORDERID MEDIUMINT UNSIGNED NOT NULL,
   ORDERCATEGORYNAME VARCHAR(255) NOT NULL,	-- max=21
   SECONDARYORDERCATEGORYNAME VARCHAR(255),	-- max=0
   ORDERCATEGORYDESCRIPTION VARCHAR(255) NOT NULL,	-- max=12
   ISOPENBAG TINYINT UNSIGNED NOT NULL,
   CONTINUEINNEXTDEPT TINYINT UNSIGNED NOT NULL,
   CANCELREASON TINYINT UNSIGNED NOT NULL,
   STATUSDESCRIPTION VARCHAR(255) NOT NULL,	-- max=15
   COMMENTS_EDITEDBY VARCHAR(255),	-- max=7
   COMMENTS_CANCELEDBY VARCHAR(255),	-- max=17
   COMMENTS_DATE DATETIME,
  UNIQUE KEY PROCEDUREEVENTS_MV_ROW_ID (ROW_ID),	-- nvals=258066
  UNIQUE KEY PROCEDUREEVENTS_MV_ORDERID (ORDERID)	-- nvals=258066
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS PROCEDURES_ICD (	-- rows=240095
   ROW_ID MEDIUMINT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED NOT NULL,
   SEQ_NUM TINYINT UNSIGNED NOT NULL,
   ICD9_CODE VARCHAR(255) NOT NULL,	-- max=4
  UNIQUE KEY PROCEDURES_ICD_ROW_ID (ROW_ID)	-- nvals=240095
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS SERVICES (	-- rows=73343
   ROW_ID MEDIUMINT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED NOT NULL,
   TRANSFERTIME DATETIME NOT NULL,
   PREV_SERVICE VARCHAR(255),	-- max=5
   CURR_SERVICE VARCHAR(255) NOT NULL,	-- max=5
  UNIQUE KEY SERVICES_ROW_ID (ROW_ID)	-- nvals=73343
  )
  CHARACTER SET = UTF8;

CREATE TABLE  IF NOT EXISTS TRANSFERS (	-- rows=261897
   ROW_ID MEDIUMINT UNSIGNED NOT NULL,
   SUBJECT_ID MEDIUMINT UNSIGNED NOT NULL,
   HADM_ID MEDIUMINT UNSIGNED NOT NULL,
   ICUSTAY_ID MEDIUMINT UNSIGNED,
   DBSOURCE VARCHAR(255),	-- max=10
   EVENTTYPE VARCHAR(255),	-- max=9
   PREV_CAREUNIT VARCHAR(255),	-- max=5
   CURR_CAREUNIT VARCHAR(255),	-- max=5
   PREV_WARDID TINYINT UNSIGNED,
   CURR_WARDID TINYINT UNSIGNED,
   INTIME DATETIME,
   OUTTIME DATETIME,
   LOS FLOAT,
  UNIQUE KEY TRANSFERS_ROW_ID (ROW_ID)	-- nvals=261897
  )
  CHARACTER SET = UTF8;

